# Generated by Django 5.0.7 on 2024-07-23 16:09

import crochet_blaise.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patterns_Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patterns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn', to='crochet_blaise.patterns')),
            ],
        ),
        migrations.AddField(
            model_name='patterns',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='crochet_blaise.profile'),
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=30)),
                ('description', models.TextField()),
                ('skill_level', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('EXP', 'Expert')], default='Beginner', max_length=3)),
                ('patterns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='crochet_blaise.patterns')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=30)),
                ('description', models.TextField()),
                ('brand', models.CharField()),
                ('techniques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='crochet_blaise.techniques')),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=60)),
                ('brand', models.CharField(verbose_name=30)),
                ('colour', models.CharField(verbose_name=15)),
                ('price', models.IntegerField(validators=[crochet_blaise.models.validate_positive])),
                ('size', models.CharField(verbose_name=30)),
                ('patterns_yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn', to='crochet_blaise.patterns_yarn')),
            ],
        ),
    ]
