# Generated by Django 5.0.7 on 2024-07-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_blaise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns_yarn',
            name='name',
            field=models.CharField(default='name', verbose_name=30),
            preserve_default=False,
        ),
    ]
