# Generated by Django 5.0.7 on 2024-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_blaise', '0005_patterns_description_alter_techniques_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='skill_level',
            field=models.CharField(choices=[('INT', 'Intermediate'), ('EXP', 'Expert'), ('BEG', 'Beginner')], default='Beginner', max_length=3),
        ),
    ]
