# Generated by Django 5.0.7 on 2024-07-26 23:09

import crochet_blaise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_blaise', '0006_alter_techniques_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='techniques',
        ),
        migrations.AddField(
            model_name='patterns',
            name='image',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patterns',
            name='price',
            field=models.IntegerField(default=0, validators=[crochet_blaise.models.validate_positive]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yarn',
            name='image',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Techniques',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
