# Generated by Django 5.0.7 on 2024-07-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_blaise', '0007_remove_tools_techniques_patterns_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns',
            name='onSale',
            field=models.BooleanField(default=False),
        ),
    ]
