# Generated by Django 5.0.7 on 2024-07-29 13:27

import crochet_blaise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_blaise', '0008_patterns_onsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterns',
            name='price',
            field=models.IntegerField(default=0, validators=[crochet_blaise.models.validate_positive]),
        ),
    ]
