# Generated by Django 5.0.7 on 2024-07-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_blaise', '0009_alter_patterns_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patterns',
            old_name='image',
            new_name='picture',
        ),
    ]
