# Generated by Django 5.0.7 on 2024-07-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_blaise', '0011_rename_picture_patterns_patternpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patterns',
            old_name='patternPicture',
            new_name='image',
        ),
    ]
