# Generated by Django 5.0.7 on 2024-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_blaise', '0012_rename_patternpicture_patterns_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterns',
            name='image',
            field=models.CharField(default='placeholder', max_length=200),
        ),
    ]
